defaults:
  - pushT_driftworld
  - _self_

model:
  dir_name: pushT_driftflow_posttrain_seed1
  objective: drift_flow
  drift_flow:
    endpoint_replay_probability: 0.25
    grid_replay_probability: 0.0
    positive_particles: 1
    transport_parameterization: residual
    time_sampling: logit_normal
    time_mu: -0.4
    time_sigma: 1.0

train:
  seed: 1
  max_steps: 100000
  init_checkpoint: /storage/scratch1/9/eliu354/driftflowworld/checkpoints/official/pusht_checkpoints/pushT_driftworld/ckpt_save/ckpt-step1180500.pth

opt:
  lr: 0.0000025

data:
  dataset_path_dir: /storage/scratch1/9/eliu354/driftflowworld/data/world_model_data/dataset_domain/all_data

wandb_info:
  entity: null
  project: driftflowworld-pusht
  name: driftflow-posttrain-seed1
  key: null

output_dir: /storage/scratch1/9/eliu354/driftflowworld/checkpoints/${model.dir_name}

eval:
  checkpoint: "${path_ckpt_latest}"
  nfe: 1
  num_videos: 1000
  metrics_dir: /storage/scratch1/9/eliu354/driftflowworld/runs/metrics/${model.dir_name}
  reward_predictor_xy_checkpoint: /storage/scratch1/9/eliu354/driftflowworld/checkpoints/official/pusht_checkpoints/reward/reward_predictor_xy.pth
  reward_predictor_angle_checkpoint: /storage/scratch1/9/eliu354/driftflowworld/checkpoints/official/pusht_checkpoints/reward/reward_predictor_angle.pth
